services:
  web:
    build: .
    container_name: meeting-notes-api
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - .:/app
      - ~/.cache/huggingface:/root/.cache/huggingface
    restart: always

  worker:
    build: .
    container_name: meeting-notes-worker
    command: celery -A app.tasks.celery_app worker --loglevel=info
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - .:/app
      - ~/.cache/huggingface:/root/.cache/huggingface
    restart: always

  redis:
    image: redis:7-alpine
    container_name: meeting-notes-redis
    ports:
      - "6379:6379"
    restart: always
